server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/magicskunk/cloud-config
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"
